version: '3.4'

services:
  apidasuka:
    image: apidasuka
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6001:6001
      - 9229:9229
    command: ["npm", "start"] 